cmake: fix link dependencies
* link libosd against libos
  OSD.cc references FuseStore, so libosd should link against libos.
* link rbd_replay against rbd_replay_types, because
  rbd_replay/Replayer.cc reference rbd_replay::action::ActionEntry::decode()
* link libmon against libkv, otherwise we could have:
../../lib/libmon.a(RocksDBStore.cc.o): In function
`RocksDBStore::get_wholespace_iterator()':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/kv/RocksDBStore.cc:1451:
undefined reference to `rocksdb::ReadOptions::ReadOptions()'

Signed-off-by: Kefu Chai <kchai@redhat.com>